"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import estela_client
from estela_client.model.user_detail import UserDetail
globals()['UserDetail'] = UserDetail
from estela_client.model.project_update import ProjectUpdate


class TestProjectUpdate(unittest.TestCase):
    """ProjectUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectUpdate(self):
        """Test ProjectUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
