"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import estela_client
from estela_client.model.spider_job_arg import SpiderJobArg
from estela_client.model.spider_job_env_var import SpiderJobEnvVar
from estela_client.model.spider_job_tag import SpiderJobTag
globals()['SpiderJobArg'] = SpiderJobArg
globals()['SpiderJobEnvVar'] = SpiderJobEnvVar
globals()['SpiderJobTag'] = SpiderJobTag
from estela_client.model.spider_cron_job_create import SpiderCronJobCreate


class TestSpiderCronJobCreate(unittest.TestCase):
    """SpiderCronJobCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpiderCronJobCreate(self):
        """Test SpiderCronJobCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SpiderCronJobCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
