"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import estela_client
from estela_client.model.user_detail import UserDetail


class TestUserDetail(unittest.TestCase):
    """UserDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserDetail(self):
        """Test UserDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
