"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import estela_client
from estela_client.api.spiders_api import SpidersApi  # noqa: E501


class TestSpidersApi(unittest.TestCase):
    """SpidersApi unit test stubs"""

    def setUp(self):
        self.api = SpidersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_projects_spiders_list(self):
        """Test case for api_projects_spiders_list

        """
        pass

    def test_api_projects_spiders_partial_update(self):
        """Test case for api_projects_spiders_partial_update

        """
        pass

    def test_api_projects_spiders_read(self):
        """Test case for api_projects_spiders_read

        """
        pass

    def test_api_projects_spiders_update(self):
        """Test case for api_projects_spiders_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
