"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import estela_client
from estela_client.model.delete_job_data import DeleteJobData


class TestDeleteJobData(unittest.TestCase):
    """DeleteJobData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteJobData(self):
        """Test DeleteJobData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteJobData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
