"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import estela_client
from estela_client.model.spider_cron_job import SpiderCronJob
globals()['SpiderCronJob'] = SpiderCronJob
from estela_client.model.project_cron_job import ProjectCronJob


class TestProjectCronJob(unittest.TestCase):
    """ProjectCronJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectCronJob(self):
        """Test ProjectCronJob"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectCronJob()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
