"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import estela_client
from estela_client.api.deploys_api import DeploysApi  # noqa: E501


class TestDeploysApi(unittest.TestCase):
    """DeploysApi unit test stubs"""

    def setUp(self):
        self.api = DeploysApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_projects_deploys_create(self):
        """Test case for api_projects_deploys_create

        """
        pass

    def test_api_projects_deploys_delete(self):
        """Test case for api_projects_deploys_delete

        """
        pass

    def test_api_projects_deploys_list(self):
        """Test case for api_projects_deploys_list

        """
        pass

    def test_api_projects_deploys_partial_update(self):
        """Test case for api_projects_deploys_partial_update

        """
        pass

    def test_api_projects_deploys_read(self):
        """Test case for api_projects_deploys_read

        """
        pass

    def test_api_projects_deploys_update(self):
        """Test case for api_projects_deploys_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
