"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import estela_client
from estela_client.api.spider_jobs_api import SpiderJobsApi  # noqa: E501


class TestSpiderJobsApi(unittest.TestCase):
    """SpiderJobsApi unit test stubs"""

    def setUp(self):
        self.api = SpiderJobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_projects_spiders_jobs_create(self):
        """Test case for api_projects_spiders_jobs_create

        """
        pass

    def test_api_projects_spiders_jobs_data_delete(self):
        """Test case for api_projects_spiders_jobs_data_delete

        """
        pass

    def test_api_projects_spiders_jobs_data_list(self):
        """Test case for api_projects_spiders_jobs_data_list

        """
        pass

    def test_api_projects_spiders_jobs_list(self):
        """Test case for api_projects_spiders_jobs_list

        """
        pass

    def test_api_projects_spiders_jobs_partial_update(self):
        """Test case for api_projects_spiders_jobs_partial_update

        """
        pass

    def test_api_projects_spiders_jobs_read(self):
        """Test case for api_projects_spiders_jobs_read

        """
        pass

    def test_api_projects_spiders_jobs_update(self):
        """Test case for api_projects_spiders_jobs_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
