"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import estela_client
from estela_client.model.user_profile import UserProfile


class TestUserProfile(unittest.TestCase):
    """UserProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserProfile(self):
        """Test UserProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserProfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
