"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import estela_client
from estela_client.model.spider_update import SpiderUpdate


class TestSpiderUpdate(unittest.TestCase):
    """SpiderUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpiderUpdate(self):
        """Test SpiderUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SpiderUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
