"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import estela_client
from estela_client.api.spider_cronjobs_api import SpiderCronjobsApi  # noqa: E501


class TestSpiderCronjobsApi(unittest.TestCase):
    """SpiderCronjobsApi unit test stubs"""

    def setUp(self):
        self.api = SpiderCronjobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_projects_spiders_cronjobs_create(self):
        """Test case for api_projects_spiders_cronjobs_create

        """
        pass

    def test_api_projects_spiders_cronjobs_delete(self):
        """Test case for api_projects_spiders_cronjobs_delete

        """
        pass

    def test_api_projects_spiders_cronjobs_list(self):
        """Test case for api_projects_spiders_cronjobs_list

        """
        pass

    def test_api_projects_spiders_cronjobs_partial_update(self):
        """Test case for api_projects_spiders_cronjobs_partial_update

        """
        pass

    def test_api_projects_spiders_cronjobs_read(self):
        """Test case for api_projects_spiders_cronjobs_read

        """
        pass

    def test_api_projects_spiders_cronjobs_run_once(self):
        """Test case for api_projects_spiders_cronjobs_run_once

        """
        pass

    def test_api_projects_spiders_cronjobs_update(self):
        """Test case for api_projects_spiders_cronjobs_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
