"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import estela_client
from estela_client.model.spider import Spider
globals()['Spider'] = Spider
from estela_client.model.inline_response2003 import InlineResponse2003


class TestInlineResponse2003(unittest.TestCase):
    """InlineResponse2003 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003(self):
        """Test InlineResponse2003"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
