"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import estela_client
from estela_client.model.inline_response401 import InlineResponse401


class TestInlineResponse401(unittest.TestCase):
    """InlineResponse401 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse401(self):
        """Test InlineResponse401"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse401()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
