"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import estela_client
from estela_client.api.auth_api import AuthApi  # noqa: E501


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_account_change_password_change(self):
        """Test case for api_account_change_password_change

        """
        pass

    def test_api_account_reset_password_confirm(self):
        """Test case for api_account_reset_password_confirm

        """
        pass

    def test_api_account_reset_password_request(self):
        """Test case for api_account_reset_password_request

        """
        pass

    def test_api_account_reset_password_validate(self):
        """Test case for api_account_reset_password_validate

        """
        pass

    def test_api_auth_activate(self):
        """Test case for api_auth_activate

        """
        pass

    def test_api_auth_login(self):
        """Test case for api_auth_login

        """
        pass

    def test_api_auth_profile_create(self):
        """Test case for api_auth_profile_create

        """
        pass

    def test_api_auth_profile_delete(self):
        """Test case for api_auth_profile_delete

        """
        pass

    def test_api_auth_profile_list(self):
        """Test case for api_auth_profile_list

        """
        pass

    def test_api_auth_profile_partial_update(self):
        """Test case for api_auth_profile_partial_update

        """
        pass

    def test_api_auth_profile_read(self):
        """Test case for api_auth_profile_read

        """
        pass

    def test_api_auth_profile_update(self):
        """Test case for api_auth_profile_update

        """
        pass

    def test_api_auth_register(self):
        """Test case for api_auth_register

        """
        pass


if __name__ == '__main__':
    unittest.main()
