"""
    estela API v1.0 Documentation

    estela API Swagger Specification  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import estela_client
from estela_client.api.projects_api import ProjectsApi  # noqa: E501


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_projects_create(self):
        """Test case for api_projects_create

        """
        pass

    def test_api_projects_cronjobs(self):
        """Test case for api_projects_cronjobs

        """
        pass

    def test_api_projects_current_usage(self):
        """Test case for api_projects_current_usage

        """
        pass

    def test_api_projects_delete(self):
        """Test case for api_projects_delete

        """
        pass

    def test_api_projects_jobs(self):
        """Test case for api_projects_jobs

        """
        pass

    def test_api_projects_list(self):
        """Test case for api_projects_list

        """
        pass

    def test_api_projects_partial_update(self):
        """Test case for api_projects_partial_update

        """
        pass

    def test_api_projects_read(self):
        """Test case for api_projects_read

        """
        pass

    def test_api_projects_update(self):
        """Test case for api_projects_update

        """
        pass

    def test_api_projects_usage(self):
        """Test case for api_projects_usage

        """
        pass


if __name__ == '__main__':
    unittest.main()
